services:        
# MongoDB service
    mongo_db:
        container_name: db_container
        image: mongo:latest
        ports:
          - 27017:27017
        restart: always
        volumes:
            - mongo_db:/data/db
    
    # Node API service
    api:
        container_name: mypharm_web
        build: .
        restart: always
        ports:
            - 3000:3000
        environment:
            PORT: 3000
            MONGODB_URI: mongodb://mongo_db:27017
            DB_NAME: mypharm_db
            NAME: MyPharm
        depends_on:
            - mongo_db

volumes:
    mongo_db: {}
